/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(cpfsk_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f0953b2760dea487fa7d68e4fb7ad5ee)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/spread/cpfsk_demod.h>
// pydoc.h is automatically generated in the build directory
#include <cpfsk_demod_pydoc.h>

void bind_cpfsk_demod(py::module& m)
{

    using cpfsk_demod    = gr::spread::cpfsk_demod;


    py::class_<cpfsk_demod, gr::sync_decimator,
        std::shared_ptr<cpfsk_demod>>(m, "cpfsk_demod", D(cpfsk_demod))

        .def(py::init(&cpfsk_demod::make),
           D(cpfsk_demod,make)
        )
        



        ;




}








