/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rx_synthesizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(710de7f07e3712aa5abeb6dc1c8887a9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/spread/rx_synthesizer.h>
// pydoc.h is automatically generated in the build directory
#include <rx_synthesizer_pydoc.h>

void bind_rx_synthesizer(py::module& m)
{

    using rx_synthesizer    = gr::spread::rx_synthesizer;


    py::class_<rx_synthesizer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rx_synthesizer>>(m, "rx_synthesizer", D(rx_synthesizer))

        .def(py::init(&rx_synthesizer::make),
           D(rx_synthesizer,make)
        )
        



        ;




}








