/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(synthesizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3faa70169402e43fc66d7110b74bb2b5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/spread/synthesizer.h>
// pydoc.h is automatically generated in the build directory
#include <synthesizer_pydoc.h>

void bind_synthesizer(py::module& m)
{

    using synthesizer    = gr::spread::synthesizer;


    py::class_<synthesizer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<synthesizer>>(m, "synthesizer", D(synthesizer))

        .def(py::init(&synthesizer::make),
           D(synthesizer,make)
        )
        



        ;




}








